# Примеры использования и доступ к элементам массива

In [2]:
import numpy as np
arr = np.array([1, 2, 3, 4])

In [3]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
result = arr1 + arr2
print(result)

[5 7 9]


In [4]:
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])
result = np.dot(matrix1, matrix2)
print(result)

[[19 22]
 [43 50]]


In [5]:
data = np.array([1, 2, 3, 4, 5])
mean = np.mean(data)
std_dev = np.std(data)
print(mean, std_dev)

3.0 1.4142135623730951


In [6]:
arr = np.array([1, 2, 3, 4])
result = arr * 2
print(result)

[2 4 6 8]


In [7]:
m = np.matrix('1 2 3 4; 5 6 7 8; 9 1 5 7')
print(m)

[[1 2 3 4]
 [5 6 7 8]
 [9 1 5 7]]


In [8]:
m[1, 0]

5

In [9]:
m[1, :]

matrix([[5, 6, 7, 8]])

In [10]:
m[:, 2]

matrix([[3],
        [7],
        [5]])

In [11]:
m[1, 2:]

matrix([[7, 8]])

In [12]:
m[0:2, 1]

matrix([[2],
        [6]])

In [13]:
m[0:2, 1:3]

matrix([[2, 3],
        [6, 7]])

In [14]:
cols = [0, 1, 3]
m[:, cols]

matrix([[1, 2, 4],
        [5, 6, 8],
        [9, 1, 7]])

# Расчёт статистик по данным в массиве

In [15]:
m = np.matrix('1 2 3 4; 5 6 7 8; 9 1 5 7')
print(m)

[[1 2 3 4]
 [5 6 7 8]
 [9 1 5 7]]


In [16]:
type(m)

numpy.matrix

In [17]:
m = np.array(m)
type(m)

numpy.ndarray

In [18]:
m.shape

(3, 4)

In [19]:
m.max()

9

In [20]:
np.max(m)

9

In [21]:
m.max()

9

In [22]:
m.max(axis=1)

array([4, 8, 9])

In [23]:
m.max(axis=0)

array([9, 6, 7, 8])

In [24]:
m.mean()

4.833333333333333

In [25]:
m.mean(axis=1)

array([2.5, 6.5, 5.5])

In [26]:
m.sum()

58

In [27]:
m.sum(axis=0)

array([15,  9, 15, 19])

# Использование boolean массива для доступа к ndarray

In [29]:
import numpy as np
nums = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
letters = np.array(['a', 'b', 'c', 'd', 'a', 'e', 'b'])

In [30]:
less_then_5 = nums < 5
less_then_5

array([ True,  True,  True,  True, False, False, False, False, False,
       False])

In [31]:
pos_a = letters == 'a'
pos_a

array([ True, False, False, False,  True, False, False])

In [32]:
nums[less_then_5]

array([1, 2, 3, 4])

In [33]:
print(m)

[[1 2 3 4]
 [5 6 7 8]
 [9 1 5 7]]


In [34]:
mod_m = np.logical_and(m>=3, m<=7)
mod_m

array([[False, False,  True,  True],
       [ True,  True,  True, False],
       [False, False,  True,  True]])

In [35]:
m[mod_m]

array([3, 4, 5, 6, 7, 5, 7])

In [36]:
nums[nums < 5]

array([1, 2, 3, 4])

In [37]:
nums[nums < 5] = 10
print(nums)

[10 10 10 10  5  6  7  8  9 10]


In [38]:
m[m > 7] = 25
print(m)

[[ 1  2  3  4]
 [ 5  6  7 25]
 [25  1  5  7]]


# Допольнительные функции

In [ ]:
import numpy as np

In [41]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
np.arange(5, 12)

array([ 5,  6,  7,  8,  9, 10, 11])

In [43]:
np.arange(1, 5, 0.5)

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [44]:
a = [[1, 2], [3, 4]]
np.matrix(a)

matrix([[1, 2],
        [3, 4]])

In [45]:
b = np.array([[5, 6], [7,8]])
np.matrix(b)

matrix([[5, 6],
        [7, 8]])

In [46]:
np.matrix('[1, 2; 3, 4]')

matrix([[1, 2],
        [3, 4]])

In [47]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [48]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [49]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [50]:
np.ravel(A)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [51]:
a = np.random.rand(10)
a

array([0.22489975, 0.00836441, 0.50264354, 0.66557434, 0.65243536,
       0.24276517, 0.85383872, 0.57885355, 0.43800649, 0.53098295])

In [52]:
np.where(a > 0.5, True, False)

array([False, False,  True,  True,  True, False,  True,  True, False,
        True])

In [54]:
x = np.linspace(0, 1, 5)
x

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [55]:
np.random.permutation(7)

array([4, 0, 1, 2, 3, 6, 5])

In [56]:
a = ['a', 'b', 'c', 'd', 'e']
np.random.permutation(a)

array(['a', 'b', 'c', 'd', 'e'], dtype='<U1')

# Вектор

In [57]:
import numpy as np
v_hor_np = np.array([1, 2])
print(v_hor_np)

[1 2]


In [58]:
v_hor_zeros_v1 = np.zeros((5,))
print(v_hor_zeros_v1 )

[0. 0. 0. 0. 0.]


In [59]:
v_hor_zeros_v2 = np.zeros((1, 5))
print(v_hor_zeros_v2 )

[[0. 0. 0. 0. 0.]]


In [60]:
v_hor_one_v1 = np.ones((5,))
print(v_hor_one_v1)

[1. 1. 1. 1. 1.]


In [61]:
v_hor_one_v1 = np.ones((5,))
print(v_hor_one_v1)

[1. 1. 1. 1. 1.]


In [62]:
v_hor_one_v2 = np.ones((1, 5))
print(v_hor_one_v2)

[[1. 1. 1. 1. 1.]]


In [63]:
v_vert_np = np.array([[1], [2]])
print(v_vert_np)

[[1]
 [2]]


In [64]:
v_vert_zeros = np.zeros((5, 1))
print(v_vert_zeros)

[[0.]
 [0.]
 [0.]
 [0.]
 [0.]]


In [65]:
v_vert_ones = np.ones((5, 1))
print(v_vert_ones)

[[1.]
 [1.]
 [1.]
 [1.]
 [1.]]


# Квадратная матрица

In [66]:
m_sqr_arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(m_sqr_arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [67]:
m_sqr = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
m_sqr_arr = np.array(m_sqr)
print(m_sqr_arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [68]:
m_sqr_mx = np.matrix([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(m_sqr_mx)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [69]:
m_sqr_mx = np.matrix('1 2 3; 4 5 6; 7 8 9')
print(m_sqr_mx)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


# Диагональная матрица

In [70]:
m_diag = [[1, 0, 0], [0, 5, 0], [0, 0, 9]]
m_diag_np = np.matrix(m_diag)
print(m_diag_np)

[[1 0 0]
 [0 5 0]
 [0 0 9]]


In [71]:
m_sqr_mx = np.matrix('1 2 3; 4 5 6; 7 8 9')
diag = np.diag(m_sqr_mx)
print(diag)

[1 5 9]


In [72]:
m_diag_np = np.diag(np.diag(m_sqr_mx))
print(m_diag_np)

[[1 0 0]
 [0 5 0]
 [0 0 9]]


# Единичаная матрица

In [73]:
m_e = [[1, 0, 0], [0, 1, 0], [0, 0, 1]]
m_e_np = np.matrix(m_e)
print(m_e_np)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [74]:
m_eye = np.eye(3)
print(m_eye)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [75]:
m_idnt = np.identity(3)
print(m_idnt)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


# Нулевая матрица

In [76]:
m_zeros = np.zeros((3, 3))
print(m_zeros)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


# Заданеие матрицы в общем виде

In [77]:
m_mx = np.matrix('1 2 3; 4 5 6')
print(m_mx)

[[1 2 3]
 [4 5 6]]


In [78]:
m_var = np.zeros((2, 5))
print(m_var)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


# Транспонирование матрицы

In [79]:
A = np.matrix('1 2 3; 4 5 6')
print(A)

[[1 2 3]
 [4 5 6]]


In [80]:
A_t = A.transpose()
print(A_t)

[[1 4]
 [2 5]
 [3 6]]


In [81]:
print(A.T)

[[1 4]
 [2 5]
 [3 6]]


**Свойство 1.** Дважды транспонированная матрица равана исходной матрице:

In [82]:
R = (A.T).T
print(R)

[[1 2 3]
 [4 5 6]]


**Свойство 2.** Транспонирование суммы матриц равно сумме транспонированных матриц:

In [83]:
A = np.matrix('1 2 3; 4 5 6')
B = np.matrix('7 8 9; 0 7 5')
L = (A + B).T
R = A.T + B.T
print(L)

[[ 8  4]
 [10 12]
 [12 11]]


In [84]:
print(R)

[[ 8  4]
 [10 12]
 [12 11]]


**Свойство 3.** Транспонирование произведения матриц равно произведению транспонированных матриц расставленных в обратном порядке:

In [87]:
A = np.matrix('1 2; 3 4')
B = np.matrix('5 6; 7 8')
L = (A.dot(B)).T
R = (B.T).dot(A.T)
print(L)

[[19 43]
 [22 50]]


In [88]:
print(R)

[[19 43]
 [22 50]]


**Свойство 4.** Транспонирование произведения матрицы на чсило равно произведению этого числа на транспонированную матрицу:

In [89]:
A = np.matrix('1 2 3; 4 5 6')
k = 3
L = (k * A).T
R = k * (A.T)
print(L)

[[ 3 12]
 [ 6 15]
 [ 9 18]]


In [90]:
print(R)

[[ 3 12]
 [ 6 15]
 [ 9 18]]


**Свойство 5.** Определеители исходной и транспонированной матрицы совпадают:

In [91]:
A = np.matrix('1 2; 3 4')
A_det = np.linalg.det(A)
A_T_det = np.linalg.det(A.T)
print(f"{A_det:.9f}")

-2.000000000


In [92]:
print(f"{A_T_det:.9f}")

-2.000000000


# Действия над матрицами

In [93]:
A = np.matrix('1 2 3; 4 5 6')
C = 3 * A
print(C)

[[ 3  6  9]
 [12 15 18]]


**Свойство 1.** Произведение единицы и любой заданной матрицы равно заданной матрице:

In [94]:
A = np.matrix('1 2; 3 4')
L = 1 * A
R = A
print(L)

[[1 2]
 [3 4]]


In [95]:
print(R)

[[1 2]
 [3 4]]


**Свойство 2.** Произведение нуля и любой матрицы равно нулевой матрице, размерность которой равна исходной матрицы:

In [96]:
A = np.matrix('1 2; 3 4')
Z = np.matrix('0 0; 0 0')
L = 0 * A
R = Z
print(L)

[[0 0]
 [0 0]]


In [97]:
print(R)

[[0 0]
 [0 0]]


**Свойство 3.** Произведение матрицы на сумму чисел равно сумме произведений матрицы на каждое из этих чисел:

In [98]:
A = np.matrix('1 2; 3 4')
p = 2
q = 3
L = (p + q) * A
R = p * A + q * A
print(L)

[[ 5 10]
 [15 20]]


In [99]:
print(R)

[[ 5 10]
 [15 20]]


**Свойство 4.** Произведение матрицы на произведение двух чисел равно произведению второго числа и заданной матрицы, умноженному на первое число:

In [100]:
L = (p * q) * A
R = p * (q * A)
print(L)

[[ 6 12]
 [18 24]]


In [101]:
print(R)

[[ 6 12]
 [18 24]]


**Свойство 5.** Произведение суммы матриц на число равно сумме произведений этих матриц на заданное число:

In [102]:
A = np.matrix('1 2; 3 4')
B = np.matrix('5 6; 7 8')
k = 3
L = k * (A + B)
R = k * A + k * B
print(L)

[[18 24]
 [30 36]]


In [103]:
print(R)

[[18 24]
 [30 36]]


# Сложение матриц

In [104]:
A = np.matrix('1 6 3; 8 2 7')
B = np.matrix('8 1 5; 6 9 12')
C = A + B
print(C)

[[ 9  7  8]
 [14 11 19]]


**Свойство 1.** Коммутативность сложения. От перестановки матриц их сумма не изменяется:

In [105]:
A = np.matrix('1 2; 3 4')
B = np.matrix('5 6; 7 8')
L = A + B
R = B + A
print(L)

[[ 6  8]
 [10 12]]


In [106]:
print(R)

[[ 6  8]
 [10 12]]


**Свойство 2.** Ассоциативность сложения. Результат сложения трех и более матриц не зависит от порядка, в котором эта операция будет выполняться:

In [107]:
A = np.matrix('1 2; 3 4')
B = np.matrix('5 6; 7 8')
C = np.matrix('1 7; 9 3')
L = A + (B + C)
R = (A + B) + C
print(L)

[[ 7 15]
 [19 15]]


In [108]:
print(R)

[[ 7 15]
 [19 15]]


**Свойство 3.** Для любой матрицы существует противоположная ей , такая, что их сумма является нулевой матрицей:

In [109]:
A = np.matrix('1 2; 3 4')
Z = np.matrix('0 0; 0 0')
L = A + (-1)*A
print(L)

[[0 0]
 [0 0]]


In [110]:
print(Z)

[[0 0]
 [0 0]]


# Умножение матриц

In [111]:
A = np.matrix('1 2 3; 4 5 6')
B = np.matrix('7 8; 9 1; 2 3')
C = A.dot(B)
print(C)

[[31 19]
 [85 55]]


**Свойство 1.** Ассоциативность умножения. Результат умножения матриц не зависит от порядка, в котором будет выполняться эта операция:

In [112]:
A = np.matrix('1 2; 3 4')
B = np.matrix('5 6; 7 8')
C = np.matrix('2 4; 7 8')
L = A.dot(B.dot(C))
R = (A.dot(B)).dot(C)
print(L)

[[192 252]
 [436 572]]


In [113]:
print(R)

[[192 252]
 [436 572]]


**Свойство 2.** Дистрибутивность умножения. Произведение матрицы на сумму матриц равно сумме произведений матриц:

In [114]:
L = A.dot(B + C)
R = A.dot(B) + A.dot(C)
print(L)

[[35 42]
 [77 94]]


In [115]:
print(R)

[[35 42]
 [77 94]]


**Свойство 3.** Умножение матриц в общем виде не коммутативно. Это означает, что для матриц не выполняется правило независимости произведения от перестановки множителей:

In [116]:
L = A.dot(B)
R = B.dot(A)
print(L)

[[19 22]
 [43 50]]


In [117]:
print(R)

[[23 34]
 [31 46]]


**Свойство 4.** Произведение заданной матрицы на единичную равно исходной матрице:

In [118]:
A = np.matrix('1 2; 3 4')
E = np.matrix('1 0; 0 1')
L = E.dot(A)
R = A.dot(E)
print(L)

[[1 2]
 [3 4]]


In [119]:
print(R)

[[1 2]
 [3 4]]


In [120]:
print(A)

[[1 2]
 [3 4]]


**Свойство 5.** Произведение заданной матрицы на нулевую матрицу равно нулевой матрице:

In [121]:
A = np.matrix('1 2; 3 4')
Z = np.matrix('0 0; 0 0')
L = Z.dot(A)
R = A.dot(Z)
print(L)

[[0 0]
 [0 0]]


In [122]:
print(R)

[[0 0]
 [0 0]]


In [123]:
print(Z)

[[0 0]
 [0 0]]


# Определитель матрицы

In [124]:
A = np.matrix('-4 -1 2; 10 4 -1; 8 3 1')
print(A)

[[-4 -1  2]
 [10  4 -1]
 [ 8  3  1]]


In [125]:
np.linalg.det(A)

-14.000000000000009

## Свойства определителя матрицы

**Свойство 1.** Определитель матрицы остается неизменным при ее транспонировании:

In [126]:
A = np.matrix('-4 -1 2; 10 4 -1; 8 3 1')
print(A)

[[-4 -1  2]
 [10  4 -1]
 [ 8  3  1]]


In [127]:
print(A.T)

[[-4 10  8]
 [-1  4  3]
 [ 2 -1  1]]


In [128]:
det_A = round(np.linalg.det(A), 3)
det_A_t = round(np.linalg.det(A.T), 3)
print(det_A)

-14.0


In [129]:
print(det_A_t)

-14.0


**Свойство 2.** Если у матрицы есть строка или столбец, состоящие из нулей, то определитель такой матрицы равен нулю:

In [130]:
A = np.matrix('-4 -1 2; 0 0 0; 8 3 1')
print(A)

[[-4 -1  2]
 [ 0  0  0]
 [ 8  3  1]]


In [131]:
np.linalg.det(A)

0.0

**Свойство 3.** При перестановке строк матрицы знак ее определителя меняется на противоположный:

In [132]:
A = np.matrix('-4 -1 2; 10 4 -1; 8 3 1')
print(A)

[[-4 -1  2]
 [10  4 -1]
 [ 8  3  1]]


In [133]:
B = np.matrix('10 4 -1; -4 -1 2; 8 3 1')
print(B)

[[10  4 -1]
 [-4 -1  2]
 [ 8  3  1]]


In [134]:
round(np.linalg.det(A), 3)

-14.0

In [135]:
round(np.linalg.det(B), 3)

14.0

**Свойство 4.** Если у матрицы есть две одинаковые строки, то ее определитель равен нулю:

In [136]:
A = np.matrix('-4 -1 2; -4 -1 2; 8 3 1')
print(A)

[[-4 -1  2]
 [-4 -1  2]
 [ 8  3  1]]


In [137]:
np.linalg.det(A)

0.0

**Свойство 5.** Если все элементы строки или столбца матрицы умножить на какое-то число, то и определитель будет умножен на это число:

In [138]:
A = np.matrix('-4 -1 2; 10 4 -1; 8 3 1')
print(A)

[[-4 -1  2]
 [10  4 -1]
 [ 8  3  1]]


In [139]:
k = 2
B = A.copy()
B[2, :] = k * B[2, :]
print(B)

[[-4 -1  2]
 [10  4 -1]
 [16  6  2]]


In [140]:
det_A = round(np.linalg.det(A), 3)
det_B = round(np.linalg.det(B), 3)
det_A * k

-28.0

In [141]:
det_B

-28.0

**Свойство 6.** Если все элементы строки или столбца можно представить как сумму двух слагаемых, то определитель такой матрицы равен сумме определителей двух соответствующих матриц:

In [142]:
A = np.matrix('-4 -1 2; -4 -1 2; 8 3 1')
B = np.matrix('-4 -1 2; 8 3 2; 8 3 1')
C = A.copy()
C[1, :] += B[1, :]
print(C)

[[-4 -1  2]
 [ 4  2  4]
 [ 8  3  1]]


In [143]:
print(A)

[[-4 -1  2]
 [-4 -1  2]
 [ 8  3  1]]


In [144]:
print(B)

[[-4 -1  2]
 [ 8  3  2]
 [ 8  3  1]]


In [145]:
round(np.linalg.det(C), 3)

4.0

In [146]:
round(np.linalg.det(A), 3) + round(np.linalg.det(B), 3)

4.0

**Свойство 7.** Если к элементам одной строки прибавить элементы другой строки, умноженный на одно и тоже число, то определитель матрицы не изменится:

In [147]:
A = np.matrix('-4 -1 2; 10 4 -1; 8 3 1')
k = 2
B = A.copy()
B[1, :] = B[1, :] + k * B[0, :]
print(A)

[[-4 -1  2]
 [10  4 -1]
 [ 8  3  1]]


In [148]:
print(B)

[[-4 -1  2]
 [ 2  2  3]
 [ 8  3  1]]


In [149]:
round(np.linalg.det(A), 3)

-14.0

In [150]:
round(np.linalg.det(B), 3)

-14.0

**Свойство 8.** Если строка или столбец матрицы является линейной комбинацией других строк (столбцов), то определитель такой матрицы равен нулю:

In [151]:
A = np.matrix('-4 -1 2; 10 4 -1; 8 3 1')
print(A)

[[-4 -1  2]
 [10  4 -1]
 [ 8  3  1]]


In [152]:
k = 2
A[1, :] = A[0, :] + k * A[2, :]
round(np.linalg.det(A), 3)

0.0

**Свойство 9.** Если матрица содержит пропорциональные строки, то ее определитель равен нулю:

In [153]:
A = np.matrix('-4 -1 2; 10 4 -1; 8 3 1')
print(A)

[[-4 -1  2]
 [10  4 -1]
 [ 8  3  1]]


In [154]:
k = 2
A[1, :] = k * A[0, :]
print(A)

[[-4 -1  2]
 [-8 -2  4]
 [ 8  3  1]]


In [155]:
round(np.linalg.det(A), 3)

0.0

# Обратная матрица

In [156]:
A = np.matrix('1 -3; 2 5')
A_inv = np.linalg.inv(A)
print(A_inv)

[[ 0.45454545  0.27272727]
 [-0.18181818  0.09090909]]


**Свойство 1.** Обратная матрица обратной матрицы есть исходная матрица:

In [157]:
A = np.matrix('1. -3.; 2. 5.')
A_inv = np.linalg.inv(A)
A_inv_inv = np.linalg.inv(A_inv)
print(A)

[[ 1. -3.]
 [ 2.  5.]]


In [158]:
print(A_inv_inv)

[[ 1. -3.]
 [ 2.  5.]]


**Свойство 2.** Обратная матрица транспонированной матрицы равна транспонированной матрице от обратной матрицы:

In [159]:
A = np.matrix('1. -3.; 2. 5.')
L = np.linalg.inv(A.T)
R = (np.linalg.inv(A)).T
print(L)

[[ 0.45454545 -0.18181818]
 [ 0.27272727  0.09090909]]


In [160]:
print(R)

[[ 0.45454545 -0.18181818]
 [ 0.27272727  0.09090909]]


**Свойство 3.** Обратная матрица произведения матриц равна произведению обратных матриц:

In [161]:
A = np.matrix('1. -3.; 2. 5.')
B = np.matrix('7. 6.; 1. 8.')
L = np.linalg.inv(A.dot(B))
R = np.linalg.inv(B).dot(np.linalg.inv(A))
print(L)

[[ 0.09454545  0.03272727]
 [-0.03454545  0.00727273]]


In [162]:
print(R)

[[ 0.09454545  0.03272727]
 [-0.03454545  0.00727273]]


# Ранг матрицы

In [163]:
m_eye = np.eye(4)
print(m_eye)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [164]:
rank = np.linalg.matrix_rank(m_eye)
print(rank)

4


In [165]:
m_eye[3][3] = 0
print(m_eye)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 0.]]


In [166]:
rank = np.linalg.matrix_rank(m_eye)
print(rank)

3
